apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
  labels:
    app: game
spec:
  replicas: 3
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
        - name: cont1
          image: shammu101/cycle
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: mysvc1
spec:
  type: NodePort
  selector:
    app: game
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31100
